### ISSUE TITLE
'flip' modifier makes popper jitter when popper element has arrow margins set

### ISSUE THREAD

**Issue by PaulGiletich** [popperjs/popper.js#720]
### demo
https://popper.js.org/#example3

![ezgif com-optimize](https://user-images.githubusercontent.com/1554577/48773458-7a13a900-ecd8-11e8-984b-da085b9cad8b.gif)

### Steps to reproduce the problem

1.  move the popper to the left side of the area, right until the moment it flips
2.  move it up/down
3.  popper is jittering. probably calculation of margin for arrow is not working well with flip

### What is the expected behavior?

popper flips and stays flipped

### What went wrong?

calculation of margin for arrow is working not consistently, when flipping

**Comment by Mesoptier** [comment]
Popper.js starts its modifier chain with the given `placement` (e.g. `top`), but measures the size of the popper element as is. That is, the popper element may still have `x-placement="left"` making the dimensions slightly different than if it were `x-placement="top"`. This makes Popper.js think it actually fits with `top` placement. On the next "tick", the `x-placement` matches the initial value for `placement` and Popper.js correctly realizes it doesn't fit and flips it. Repeat.

I have fixed this locally by adding a custom modifier that resets the `x-placement` to match the value for `placement` that is being tried by Popper.js:

```js
reset: {
    order: 1,
    enabled: true,
    fn(data) {
        // This makes sure the correct CSS is applied before getting the size of the popper
        data.instance.popper.setAttribute(
            'x-placement',
            data.placement
        );
        return data;
    },
},
```

---

This should probably be implemented somewhere in Popper.js though. What do you think @FezVrasta?

**Comment by FezVrasta** [comment]
Feel free to send a PR with a proposed solution, thank you!

**Comment by Mesoptier** [comment]
@FezVrasta It's fine by me to create a PR. But before I head off on that, what do you think of the proposed solutions below? If they're completely off track I'd rather not spend too much time on them, after all :slightly_smiling_face:.

---

The `onLoad` of the `applyStyle` modifier should run before measuring the Popper dimensions, because it directly affects the dimensions. However, it is only run once when the Popper is inited. 

To be clear, the styles and the `x-placement` attribute should be applied on the Popper element:
- Before modifiers are executed in the `update()` method.
- Before re-running the modifiers in the "flip" modifier.

In other words, apply styles and attributes each time before modifiers are executed. What I could do is add a "measurePopper" modifier with `order: 0` that applies the styles and attributes before measuring the Popper and updating the `data` object.

One problem with that is the following. Usually developers will just use the `applyStyle` modifier. But they are allowed to disable it and use their own modifier to apply the DOM changes. So we can't just add the `setAttribute` call wherever we want. 

We could add a `applyStyleModifiers` option to the "measurePopper" modifier. Which would contain an array of modifiers (e.g. `computeStyles` and `applyStyles`) to run before measuring the Popper element.

This would probably be a breaking change though with devs having their own modifiers with `order: 0`.

---

Another solution would be to execute the same things I described above, but without the "measurePopper" modifier. Simply executing it in `runModifiers` before the modifiers. Something like and `applyStyleModifiers` option would still be needed.

**Comment by FezVrasta** [comment]
It may be better to wait for the v2 release

**Comment by FezVrasta** [comment]
This should by fixed with the new option that allows to define paddings for the arrow
