### ISSUE TITLE
Prevent Default Browser Behavior for Titles on Popper Elements

### ISSUE THREAD

**Issue by johndugan** [popperjs/popper.js#751]
Hi There!

I'm using Popper along with the Tooltip addon. By default, the tooltip content grabs the value from the `title` attribute on the trigger element.  Then, if a `title` value exists, when hovering over the trigger you see the Tooltip ui along with the browser's native behavior/ui for elements with the `title` attribute. Shouldn't the native behavior be prevented? Am I overlooking an option?

I believe the Tooltip api is intended to be fairly similar to Bootstraps tooltip api. This issue is not present with Boostrap. They appear to copy the value for the `title` attribute to a `data-original-title` attribute.

**Comment by FezVrasta** [comment]
Thanks for the report, it must be a bug.

**Comment by BillSnee** [comment]
Sorry if I am wrong, but I think I found something related to this issue.  Firefox dev console is reporting an issue with tooltip.js 

TypeError: this.element.getAttribute is not a function
`  _fixTitle() {
    const titleType = typeof this.element.getAttribute('data-original-title')

    if (this.element.getAttribute('title') || titleType !== 'string') {
      this.element.setAttribute(
        'data-original-title',
        this.element.getAttribute('title') || ''
      )

      this.element.setAttribute('title', '')
    }
  }`

Stack over flow tells me that jquery does not use getAttribute() but should be attr() instead.  
https://stackoverflow.com/questions/18163213/typeerror-abc-getattribute-is-not-a-function

I hope this helps.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.

**Comment by avnermosh** [comment]
I see the same problem on my side. specifically, I get the same error (`TypeError: this.element.getAttribute is not a function tooltip.js:522`) as in [here](https://github.com/popperjs/popper.js/issues/751#issuecomment-462937690)

Looking at this thread, some comments in the thread are not clear to me. 
Can somebody please clarify them?

In [here](https://github.com/popperjs/popper.js/issues/751#issue-405071160):

> > "I'm using Popper along with the Tooltip addon"

Does "Tooltip addon", refer to the tooltip within Popper ?(or some other tooltip library like the one in jQuery?)

> > "... Tooltip api is intended to be fairly similar to Bootstraps tooltip api"

What is the "Bootstraps tooltip api"? is it something different than the popper library?
According to the [Bootstrap documentation](https://getbootstrap.com/docs/4.0/components/tooltips/), to use the tooltip in Bootstrap, you have to use the popper library 

> "Tooltips rely on the 3rd party library Popper.js for positioning. You must include popper.min.js before bootstrap.js or use bootstrap.bundle.min.js / bootstrap.bundle.js which contains Popper.js in order for tooltips to work!"

is there another tooltip implementation in Bootstrap besides Popper?

In [here](https://github.com/popperjs/popper.js/issues/751#issuecomment-557480381)

> > "Please consider switching to Tippy.js, which is a way better alternative to Tooltip.js"

Is "Tooltip.js" referring to Tooltip module within popper?

And final question (because I see many questions in the Internet regarding jQuery tooltip vs Bootstrap tooltip:
Is tooltip implemtation in jQuery/jQuery-ui part of this discussion?

**Comment by FezVrasta** [comment]
1. For "Tooltip addon" they refer to Tooltip.js (see point 3);
2. Bootstrap has its own tooltip jQuery code, which uses Popper as positioning engine;
3. Tooltip.js: http://npmjs.com/tooltip.js - now deprecated tooltip library based on Popper.js;
4. Popper & Bootstrap have nothing to do with jQuery UI

**Comment by avnermosh** [comment]
Thanks for the reply. I am still a bit confused...

As I understand:

1. The tooltip.js is an _add-on within popper.js_ (*) that is now deprecated.
Other tooltip options that use popper.js are:
-- Bootstrap's own tooltip jQuery code
-- Tippy.js

2. Since I'm only including Bootstrap.bundle.js (and jQuery, but not including jQuery-ui and not including the package Tooltip.js),
this means that the tooltip that I'm using is "Bootstrap's own tooltip jQuery code"

**Please correct me if I'm wrong.**

(*) I'm saying _add-on **within** popper.js_ because:
The repository of [tooltip.js](https://www.npmjs.com/package/tooltip.js) points **directly** to [popper.js](github.com/FezVrasta/popper.js) (and not to an independent repository)

**Comment by FezVrasta** [comment]
Yes that's correct, Tooltip.js and Popper.js shared the same repository (monorepo), but with v2 it's gone.

**Comment by avnermosh** [comment]
Thanks, for clarifying.

In your comment [here](https://github.com/popperjs/popper.js/issues/751#issuecomment-557480381) you mentioned:

> Please consider switching to Tippy.js

I'm already using Bootstrap for other things, and introducing Tippy.js adds an extra package, which I would like to avoid for perfomace reasons, unless Tippy.js has advantages over Bootstrap's tooltip.

**Do you have a preference between using "Bootstrap's own tooltip jQuery code", and Tippy.js?**

**Comment by FezVrasta** [comment]
If you use Bootstrap and their tooltip are good to you, stick with them.

I suggested Tippy.js because Popper is not just a Bootstrap library, it's used by a lot of people that are not Bootstrap users.
