### ISSUE TITLE
Popper element positions incorrectly initially

### ISSUE THREAD

**Issue by jorenbroekema** [popperjs/popper.js#796]
Short description: If the viewport is pushing against the popper element prior to popper being instantiated (e.g. causing it to wrap content inside, changing its dimensions), upon first popper update, the positioning is off.

### CodePen demo
https://codepen.io/Falx/pen/ydXyXG

Sorry for not using the template, I had already made the pen before seeing this template

Here's a gif of my own implementation layer which shows it a bit more clearly (but it's not isolated code... so yea), first it renders the content, than after 3 seconds it applies popper, and then I drag the dev tools bar to change viewport slightly, making it jump: 
![2019-06-24_18-15-30](https://user-images.githubusercontent.com/36734656/60035723-ccbda500-96ad-11e9-827c-09b15c66c8b3.gif)

### Steps to reproduce the problem

1.  Make sure the popper element is visible, and that Popper has not yet been instantiated using it
2. Drag the viewport to somewhere, where you know it will cause a slide/shift of the popper el  
3. Instantiate Popper with the ref and pop el
4. Drag the viewport again slightly, and notice the sudden jump.

### What is the expected behavior?
I expected Popper to place my popper element in the right spot immediately from the moment of creating the instance, even with the viewport already pushing it.

### What went wrong?
On the first Popper update, the position is incorrect. On the second popper update (triggered by a change in viewport for example) it positions correctly. Creating the instance twice also seems to work if it is done in between the same 2 paints.

### Any other comments?
My hypothesis:
I think it may have to do with the bounding box of the popper element when the viewport is already causing overflow/wrapping behavior *prior* to popper being instantiated. The dimensions of the popper element then change upon first popper update. If it updates again, it has the right dimensions, and moves to the right spot.

**Comment by pgraci** [comment]
I can confirm this issue is happening to me as well!  In my case it's when I have a popper that gets too close to the bottom of the page.  Initial render is too low, but if I trigger a different popper on same page it works correctly.  If I go back and trigger my first popper, that one is positioned correctly as well.

**Comment by jaydlawrence** [comment]
I have had this issue when I use the popper around a pin that I give to a Bing maps implementation.
It doesn't work initially, but if I move the sidebar or re-render the popper, it works.

Maybe mine is a bit different, but the initial render has the following back from the transform part of the popper styles:
`translate3d(${left}px, ${top}px, 0)`
becomes:
`translate3d(NaNpx, NaNpx, 0)`

But mine might be because it is rendering inside an iframe or something weird.
But I thought I would add mine here, in case it is helpful and relevant.

**Comment by jaydlawrence** [comment]
> I have had this issue when I use the popper around a pin that I give to a Bing maps implementation.
> It doesn't work initially, but if I move the sidebar or re-render the popper, it works.
> 
> Maybe mine is a bit different, but the initial render has the following back from the transform part of the popper styles:
> `translate3d(${left}px, ${top}px, 0)`
> becomes:
> `translate3d(NaNpx, NaNpx, 0)`
> 
> But mine might be because it is rendering inside an iframe or something weird.
> But I thought I would add mine here, in case it is helpful and relevant.

Actually, in my case, I made the map wait until it is finished loading to render the pins (and popper) and that fixed the problem.
So it is most likely not the same issue.

**Comment by pgraci** [comment]
Thank you all.  It just made me realize the issue with mine.  I have an image rendering inside of my popper, and on initial render the image has not loaded yet.  Once it does, it pushes it out of the viewport.  Then on subsequent renders since the image has height already, it is able to calculate its position properly.  Maybe this will help someone else!

**Comment by jorenbroekema** [comment]
To more succinctly summarize what I think happens:
1) Content is rendered but viewport pushes on it making the bounding box different than it would otherwise be (due to content wrapping, native responsiveness stuff that the browser provides)
2) Popper instance is created
3) Popper initially positions the popper element based its current bounding box dimensions
4) Due to change of position, viewport no longer pushes on it and bounding box changes
5) Popper element looks wrongly positioned

What I do currently as a "6th step" if you will, is call update() on the Popper instance after I'm sure that my content has rendered and the instance exists. This method is called in the constructor of Popper class, but this extra update() seems to ensure correct position.

I am not sure how to properly fix it.. always calling update() twice seems really ugly. Perhaps Popper should check in constructor whether perhaps viewport was already pushing the popper element (get 'right' property and viewportWidth and compare), and if so, do another update() call just to make sure that it repositions the popper element if its bounding box changed due to the first reposition.

**Comment by FezVrasta** [comment]
May someone please confirm if the bug is still there in Popper 2?

Here's a demo which uses the new version:
https://codepen.io/FezVrasta/pen/mdyRGMe

I can't seem to spot the issue on either of the versions.
